In [1]:
import pandas as pd

In [18]:
df = pd.read_csv("raw_data.csv")

# je gulo NaN ase oigulo true hoye jabe baki gulo false 
df.isnull()

# count  kore je konta nai 
df.isnull().sum()

# jegulo NaN ase oigulo chara sob gulo hobe r ata row onujai print korsii 
df.dropna()
# columns a print korsii 
df.dropna(axis = 1 )



# je khan a NaN ase oikhan a feel kore dibe 
df.fillna(0)
df.fillna(100)


# specific bhbe apni just age a je khan je khan a NaN ase oikha a fill korte chachen tahole 
df["age"].fillna(0)



# now project 

clean_data = df.copy()
age_mean  = clean_data["age"].mean()
clean_data["age"]= clean_data["age"].fillna(age_mean)

# clean_data

# NaN er upor a jinish ta re shundor kore NaN er jayga print kore dey atar nam forward fill
df.ffill()

# NaN er piser a jinish ta re shundor kore NaN er jayga print kore dey atar nam backword fill
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0